// Generated by CoffeeScript 1.3.3
(function() {
  var assert, chromic, describe, errored, failed, indent, level, make_spyer, make_stubber, outdent, passed, pre, render,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  assert = require('assert');

  require('./should_be');

  require('./should_contain');

  make_spyer = require('./spy').make_spyer;

  make_stubber = require('./stub').make_stubber;

  chromic = {};

  make_stubber(chromic);

  make_spyer(chromic);

  pre = "";

  level = 0;

  outdent = function() {
    level = level - 1;
    return pre = Array(level).join("  ");
  };

  indent = function() {
    level = level + 1;
    return pre = Array(level).join("  ");
  };

  render = function(s) {
    return console.log(s);
  };

  failed = function(should) {
    return "" + pre + "  " + should + " (\x1B[0;31m \u2716 \x1B[0;0m)";
  };

  errored = function(e) {
    return "" + pre + "\x1B[0;31m  \u21b3  " + e + " \x1B[0;0m";
  };

  passed = function(should) {
    return "" + pre + "  " + should + " (\x1B[0;32m \u2714 \x1B[0;0m)";
  };

  describe = function(what) {
    return "" + pre + "\x1B[0;33m" + what + "\x1B[0;0m";
  };

  chromic.reset = function() {
    this.undo = [];
    this.invokees = [];
    this.callees = [];
    return this.nega_callees = [];
  };

  chromic.it = function(should, spec, done) {
    var callee, fn, removed, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _results;
    chromic.reset();
    try {
      spec();
      _ref = chromic.invokees;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fn = _ref[_i];
        if (fn.invoked === false) {
          throw "function not invoked";
        }
      }
      render(passed(should));
      _ref1 = chromic.callees;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        callee = _ref1[_j];
        if (!(_ref2 = callee.key, __indexOf.call(callee.object.received, _ref2) >= 0)) {
          throw "object did not receive " + callee.key;
        }
      }
      _ref3 = chromic.nega_callees;
      _results = [];
      for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
        callee = _ref3[_k];
        if (_ref4 = callee.key, __indexOf.call(callee.object.received, _ref4) >= 0) {
          throw "object should not have received " + callee.key;
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    } catch (e) {
      render(failed(should));
      return render(errored(e));
    } finally {
      _ref5 = chromic.undo;
      for (_l = 0, _len3 = _ref5.length; _l < _len3; _l++) {
        removed = _ref5[_l];
        removed["object"][removed["prop"]] = removed["original"];
      }
      if (typeof done === "function") {
        done();
      }
    }
  };

  chromic.describe = function(what, spec) {
    indent();
    render(describe(what));
    spec();
    return outdent();
  };

  (function() {
    var double, immediately;
    double = function() {
      var doubled, should_receive, shouldnt_receive;
      doubled = Object.create(this);
      Object.defineProperty(doubled, "received", {
        value: [],
        enumerable: false,
        writable: true
      });
      should_receive = function(property) {
        var receive, return_value;
        return_value = null;
        receive = function() {
          this.received.push(property);
          return return_value;
        };
        Object.defineProperty(this, property, {
          value: receive
        });
        chromic.callees.push({
          object: this,
          key: property
        });
        return {
          and_return: function(value) {
            return return_value = value;
          }
        };
      };
      shouldnt_receive = function(property) {
        var receive;
        receive = function() {
          this.received.push(property);
          return false;
        };
        Object.defineProperty(this, property, {
          value: receive
        });
        return chromic.nega_callees.push({
          object: this,
          key: property
        });
      };
      Object.defineProperty(doubled, "should_receive", {
        value: should_receive,
        enumerable: false
      });
      Object.defineProperty(doubled, "shouldReceive", {
        value: should_receive,
        enumerable: false
      });
      Object.defineProperty(doubled, "shouldnt_receive", {
        value: shouldnt_receive,
        enumerable: false
      });
      Object.defineProperty(doubled, "shouldntReceive", {
        value: shouldnt_receive,
        enumerable: false
      });
      return doubled;
    };
    Object.defineProperty(Object.prototype, "double", {
      get: double,
      set: (function() {
        return false;
      }),
      enumerable: false
    });
    (function() {
      var should_throw;
      should_throw = function(expected_message) {
        return assert.throws(this, function(e) {
          return e.message === expected_message;
        });
      };
      Object.defineProperty(Function.prototype, "should_throw", {
        value: should_throw,
        enumerable: false
      });
      return Object.defineProperty(Function.prototype, "shouldThrow", {
        value: should_throw,
        enumerable: false
      });
    })();
    Object.defineProperty(Object.prototype, "should_have_property", {
      value: (function(property) {
        return this.hasOwnProperty(property);
      }),
      enumerable: false
    });
    Object.defineProperty(Object.prototype, "shouldHaveProperty", {
      value: (function(property) {
        return this.hasOwnProperty(property);
      }),
      enumerable: false
    });
    immediately = function() {
      return function(fn, trigger) {
        return fn();
      };
    };
    return Object.defineProperty(Object.prototype, "immediately", {
      get: immediately,
      set: (function() {
        return false;
      }),
      enumerable: false
    });
  })();

  exports.it = chromic.it;

  exports.describe = chromic.describe;

  exports.stub = chromic.stub;

}).call(this);
